# Generated by Django 6.0 on 2025-12-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_no_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
